### PR TITLE
[vercel/fetch] Move @types/node-fetch to devDependencies

### PR DESCRIPTION
**Pull request by gaspar09**

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Not sure this is correct.

Since we import types from `node-fetch` and then export them again, we probably need to keep this under `peerDependencies`

https://github.com/vercel/fetch/blob/23038037ee24621a226b9ff4854a4e5657608525/packages/fetch/index.d.ts#L4

**Comment by Ethan-Arrowood** [comment]
That was my thought @styfle but why don't we make it an actual dependency then?

**Comment by styfle** [comment]
@Ethan-Arrowood For the same reason `node-fetch` is not an actual dependency: we allow the caller to pass their own implementation of fetch or they can fallback to `node-fetch`.

Each package manager handles `peerDependencies` a little differently now but its the same reason `next` has `react` and `react-dom` as `peerDependencies`.

**Comment by styfle** [comment]
I suppose we could move it to `optionalDependencies` and throw at runtime if `node-fetch` is attempted to be used but not installed

**Pull request closed without merging**
